Ensures that before and after comparisons are not including server ma…
fcrepo/Fedora-API-Test-Suite pull request #342
Opened 2021-01-15 17:32 UTC by dbernstein

…naged timestamps that change when new mementos are created when 4.3.3.1-A and 4.3.3.1-C. This filtering is necessary because Fedora 6 will update the last modified date of resources when a new version is stamped. 

Resolves:
   * https://jira.lyrasis.org/browse/FCREPO-3596
   * https://jira.lyrasis.org/browse/FCREPO-3595

2021-01-15 23:53 UTC, awoods requested changes

2021-01-15 23:53 UTC, awoods commented on src/main/java/org/fcrepo/spec/testsuite/versioning/LdpcvHttpPost.java
> +    private static final String PREFER_MINIMAL_CONTAINER_HEADER = "return=representation; " +
As you have seen, the difference between the original resource and the memento is the "last-modified" date. Such as:
```
< <http://localhost:8080/rest/testsuitecontainer01152021175807/2bd16409-e048-4bf8-b175-38c2889651d4> <http://fedora.info/definitions/v4/repository#lastModified> "2021-01-15T22:58:17.255455Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
---
> <http://localhost:8080/rest/testsuitecontainer01152021175807/2bd16409-e048-4bf8-b175-38c2889651d4> <http://fedora.info/definitions/v4/repository#lastModified> "2021-01-15T22:58:25.322368Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
```

I am a bit uncomfortable adding this Fedora-specific header into the API-Test-Suite... but the other options seem to be to post-process the RDF and ignore/remove certain values, like dates.

This works as is, but I will defer to the team if we are comfortable with this solution.

2021-01-21 14:53 UTC, awoods commented
In considering this further, filtering out the the 'lastmodified' triple may be the cleanest solution.

2021-02-10 19:03 UTC, dbernstein commented
Closing - this is resolved by https://github.com/fcrepo/fcrepo/pull/1866

2021-02-10 19:03 UTC, closed without merging