Fixes 3.6.1-A: PUT with body
fcrepo/Fedora-API-Test-Suite pull request #344
Opened 2021-01-15 19:22 UTC by dbernstein

Fixes 3.6.1-A: Fedora 5 ignores SMTs by default.  Fedora 6 does not. Therefore before PUT we are pulling back only the user triples.

Resolves: https://jira.lyrasis.org/browse/FCREPO-3592

Test by running the test suite and verifying that 3.6.1-A now passes.

2021-02-17 21:51 UTC, whikloj requested changes

2021-02-17 21:51 UTC, whikloj commented on src/main/java/org/fcrepo/spec/testsuite/crud/HttpPut.java
> +                        "omit=\"http://fedora.info/definitions/v4/repository#ServerManaged\"");
The new API prefer header for SMTs is `http://fedora.info/definitions/fcrepo#ServerManaged`
https://github.com/fcrepo/fcrepo-specification/commit/aa49ae1af5aabaa3d4b035729049d2eac95e526d#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R382

2021-02-17 23:24 UTC, dbernstein commented
@whikloj : sorry about that.  I hadn't pushed the update.  Should be good now.

2021-02-18 14:24 UTC, whikloj approved these changes
👍

2021-02-18 14:24 UTC, merged